### ISSUE TITLE
How to play Multiple videos 

### ISSUE THREAD

**Issue by altafc22** [AxonDragonScale/SyncPlayer#7]
Is there anyway to play Multiple videos synchronously in multiple devices

**Comment by zombietype** [comment]
Hey, thanks for opening an issue.

Syncplayer does not support one host playing multiple videos. However, multiple devices can host with different devices. And each client can choose a device to connect.

The functionality you ask for is not supported, and there are no plans for it either.

**Comment by zombietype** [comment]
If you can clarify the exact behavior, we may implement it.

This was a college project two semesters ago and hence is not very actively worked on.

**Comment by altafc22** [comment]
thanks for reply, i really appreciate your work. , I've changed some code in app which can play multiple videos as playlist. currently i'm working on app after finishing my work just check it out if it is useful for you simply accept my pull request.
